---------------------------------
[2024-04-16 04:08:47][INFO][200]:La conexion [dbconn_standard] esta desabilitada en el archivo .config
---------------------------------
[2024-04-16 04:08:47][INFO][200]:Iniciando ...
---------------------------------
[2024-04-16 04:08:47][INFO][200]:Comenzando la captura de las cÃ¡maras IP
---------------------------------
[2024-04-16 04:08:47][EXCEPTION][500]:PYTHON-EXCEPTION:

>>>>>>>>>>>>>>>[TRACEBACK]<<<<<<<<<<<<<<<

  File "/Users/l03542515/Documents/sw-construction-class/src/IOT-Agent/main.py", line 10, in <module>
    ProjectDirector.go( sys.argv )
  File "/Users/l03542515/Documents/sw-construction-class/src/IOT-Agent/System/Director/ProjectDirector.py", line 92, in go
    ProjectDirector().setFlux( argv )
  File "/Users/l03542515/Documents/sw-construction-class/src/IOT-Agent/System/Director/ProjectDirector.py", line 72, in setFlux
    self.__play(
  File "/Users/l03542515/Documents/sw-construction-class/src/IOT-Agent/System/Director/ProjectDirector.py", line 36, in __play
    VideoProcedures().readRTSPStreaming()
  File "/Users/l03542515/Documents/sw-construction-class/src/IOT-Agent/System/App/VideoProcedures/VideoProcedures.py", line 50, in readRTSPStreaming
    plt.imshow(self.frames['main'])

>>>>>>>>>>>>>>[ERROR_DESC]<<<<<<<<<<<<<<<

  [KeyError]:'main'

>>>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<<<<

